/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karen
 */
public class Vista extends javax.swing.JFrame {
    GeneroControlador gC;
    LibroControlador lC;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        gC = new GeneroControlador();
        lC = new LibroControlador();
        cargarGeneros();
        habilitarElementosModificarLibro(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aLCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        aLTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        aLFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aLListaGenero = new javax.swing.JComboBox<>();
        aLPrecio = new javax.swing.JTextField();
        aLbtnAgregar = new javax.swing.JButton();
        aLbtnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        eLCodigo = new javax.swing.JTextField();
        eLbtnBuscar = new javax.swing.JButton();
        eLbtnLimpiar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        eLEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mLCodigo = new javax.swing.JTextField();
        mLTitulo = new javax.swing.JTextField();
        mLFecha = new javax.swing.JTextField();
        mLPrecio = new javax.swing.JTextField();
        mLListaGenero = new javax.swing.JComboBox<>();
        mLbtnBuscar = new javax.swing.JButton();
        mLbtnModificar = new javax.swing.JButton();
        mLbtnCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lLbtnListar = new javax.swing.JButton();
        lLbtnLimpiar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jTextField10.setText("jTextField10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Título", "Fecha Publicación", "Precio", "Género"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMaxWidth(70);
            tabla.getColumnModel().getColumn(1).setMaxWidth(320);
            tabla.getColumnModel().getColumn(2).setMaxWidth(110);
            tabla.getColumnModel().getColumn(3).setMaxWidth(70);
            tabla.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("AGREGAR LIBROS");

        jLabel2.setText("Código libro:");

        jLabel3.setText("Título:");

        jLabel4.setText("Fecha Publicación:");

        jLabel5.setText("Precio:");

        jLabel6.setText("Escoger género:");

        aLListaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLListaGeneroActionPerformed(evt);
            }
        });

        aLbtnAgregar.setText("AGREGAR");
        aLbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLbtnAgregarActionPerformed(evt);
            }
        });

        aLbtnCancelar.setText("CANCELAR");
        aLbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(aLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(aLListaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(aLPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aLCodigo)
                                    .addComponent(aLTitulo)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(aLbtnAgregar)
                        .addGap(49, 49, 49)
                        .addComponent(aLbtnCancelar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(aLCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aLTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(aLPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aLListaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLbtnAgregar)
                    .addComponent(aLbtnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("ELIMINAR LIBRO");

        jLabel14.setText("Código libro:");

        eLbtnBuscar.setText("BUSCAR");
        eLbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLbtnBuscarActionPerformed(evt);
            }
        });

        eLbtnLimpiar.setText("LIMPIAR");
        eLbtnLimpiar.setToolTipText("Borrar datos búsqueda");
        eLbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLbtnLimpiarActionPerformed(evt);
            }
        });

        jLabel16.setText("La info del libro se mostrará en la tabla");

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("*");

        eLEliminar.setText("ELIMINAR");
        eLEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(eLCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(eLbtnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(eLEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(eLbtnLimpiar)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(eLCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eLbtnBuscar)
                    .addComponent(eLbtnLimpiar)
                    .addComponent(eLEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("MODIFICAR LIBRO");

        jLabel9.setText("Código libro:");

        jLabel10.setText("Título:");

        jLabel11.setText("Fecha Publicación:");

        jLabel12.setText("Precio:");

        jLabel13.setText("Género:");

        mLbtnBuscar.setText("BUSCAR");
        mLbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLbtnBuscarActionPerformed(evt);
            }
        });

        mLbtnModificar.setText("MODIFICAR");
        mLbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLbtnModificarActionPerformed(evt);
            }
        });

        mLbtnCancelar.setText("CANCELAR");
        mLbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mLCodigo)
                            .addComponent(mLTitulo)
                            .addComponent(mLFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mLbtnBuscar))
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addComponent(mLbtnModificar)
                            .addGap(38, 38, 38)
                            .addComponent(mLbtnCancelar)
                            .addGap(47, 47, 47))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mLPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mLListaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(mLbtnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(mLListaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mLbtnCancelar)
                            .addComponent(mLbtnModificar))
                        .addGap(31, 31, 31))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setText("LISTAR LIBROS");

        lLbtnListar.setText("LISTAR");
        lLbtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lLbtnListarActionPerformed(evt);
            }
        });

        lLbtnLimpiar.setText("LIMPIAR");
        lLbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lLbtnLimpiarActionPerformed(evt);
            }
        });

        jLabel18.setText("La info de los libros se mostrará en la tabla");

        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLbtnLimpiar)
                            .addComponent(lLbtnListar)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(lLbtnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lLbtnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aLListaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLListaGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aLListaGeneroActionPerformed

    private void aLbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLbtnCancelarActionPerformed
        elementosAgregarLibro();
    }//GEN-LAST:event_aLbtnCancelarActionPerformed

    private void aLbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLbtnAgregarActionPerformed
        if(aLCodigo.getText().equals("") || aLFecha.getText().equals("") || aLPrecio.getText().equals("") || aLTitulo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Primero llene todos los campos");
        }else{
            int codigoGenero = gC.devolverCodigoGenero((String)aLListaGenero.getSelectedItem());
            boolean libroCreado = lC.agregarLibro(Integer.parseInt(aLCodigo.getText()), aLTitulo.getText(), aLFecha.getText(), Double.parseDouble(aLPrecio.getText()), codigoGenero);
            if(libroCreado){
                JOptionPane.showMessageDialog(rootPane, "Libro Creado");
                elementosAgregarLibro();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Codigo libro ya existe");
                aLCodigo.setText("");
            }
        }
        
            
    }//GEN-LAST:event_aLbtnAgregarActionPerformed

    private void mLbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLbtnBuscarActionPerformed
        ResultSet libro = null;
        try {
            int codigo = Integer.parseInt(mLCodigo.getText());
            libro = lC.buscarLibro(codigo);

            if (libro != null && libro.next()) {
                habilitarElementosModificarLibro(true);
                mLTitulo.setText(libro.getString("titulo"));
                mLFecha.setText(libro.getString("fechaPublicacion"));
                mLPrecio.setText(String.valueOf(libro.getDouble("precio")));
                mLTitulo.setText(libro.getString("titulo"));
                seleccionarGeneroEnComboBox(libro.getString("genero"));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Libro no encontrado", "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
                habilitarElementosModificarLibro(false);
                mLCodigo.setText("");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, ingrese un código válido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, "Error al procesar datos del libro", ex);
            JOptionPane.showMessageDialog(rootPane, "Error al procesar datos del libro", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mLbtnBuscarActionPerformed

    private void mLbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLbtnCancelarActionPerformed
        elementosModificarLibro();
        habilitarElementosModificarLibro(false);
    }//GEN-LAST:event_mLbtnCancelarActionPerformed

    private void mLbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLbtnModificarActionPerformed
        if(mLCodigo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Primero busque un libro");
        }else{
            int codigoGenero = gC.devolverCodigoGenero((String)mLListaGenero.getSelectedItem());
            boolean cambiado = lC.modificarLibro(Integer.parseInt(mLCodigo.getText()), mLTitulo.getText(), mLFecha.getText(), Double.parseDouble(mLPrecio.getText()), codigoGenero);
        
            if(cambiado){
                JOptionPane.showMessageDialog(rootPane, "Libro modificado");
                elementosModificarLibro();
                habilitarElementosModificarLibro(false);
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudo modificar el libro");
            }
        }
    }//GEN-LAST:event_mLbtnModificarActionPerformed

    private void eLbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLbtnBuscarActionPerformed
        ResultSet libro = null;
        try {
            int codigo = Integer.parseInt(eLCodigo.getText());
            libro = lC.buscarLibro(codigo);

            if (libro != null && libro.next()) {
                mostrarDatosLibro(libro);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Libro no encontrado", "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
                elementosEliminar();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, ingrese un código válido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, "Error al procesar datos del libro", ex);
            JOptionPane.showMessageDialog(rootPane, "Error al procesar datos del libro", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eLbtnBuscarActionPerformed

    private void eLbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLbtnLimpiarActionPerformed
        elementosEliminar();
    }//GEN-LAST:event_eLbtnLimpiarActionPerformed

    private void eLEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLEliminarActionPerformed
        if(eLCodigo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Primero busque un libro");
        }else{
            boolean eliminado = lC.eliminarLibro(Integer.parseInt(eLCodigo.getText()));
            if(eliminado){
                JOptionPane.showMessageDialog(rootPane, "Libro eliminado");
                elementosEliminar();
            }
            else
                JOptionPane.showMessageDialog(rootPane,"No se pudo eliminar el libro");
        }
    }//GEN-LAST:event_eLEliminarActionPerformed

    private void lLbtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lLbtnListarActionPerformed
        ResultSet libro = lC.listarLibros();
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();

        model.setRowCount(0); 
        try {
            while(libro.next()){
                String codigoLibro = String.valueOf(libro.getInt("codigoLibro"));
                String titulo = libro.getString("titulo");
                String fechaPublicacion = libro.getString("fechaPublicacion");
                String precio = String.valueOf(libro.getDouble("precio"));
                String genero = libro.getString("descripcion");

                String[] datos = {codigoLibro, titulo, fechaPublicacion, precio, genero};
                model.addRow(datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lLbtnListarActionPerformed

    private void lLbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lLbtnLimpiarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();

        model.setRowCount(0); 
    }//GEN-LAST:event_lLbtnLimpiarActionPerformed
    
    private void elementosEliminar(){
        eLCodigo.setText("");
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
    }
    
    private void seleccionarGeneroEnComboBox(String genero) {
        for (int i = 0; i < mLListaGenero.getItemCount(); i++) {
            if (mLListaGenero.getItemAt(i).equals(genero)) {
                mLListaGenero.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void cargarGeneros(){
        ResultSet generos = gC.listarGeneros();
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) aLListaGenero.getModel();
        DefaultComboBoxModel<String> model2 = (DefaultComboBoxModel<String>) mLListaGenero.getModel();
        
        try {
            while(generos.next()){
                model.addElement(generos.getString("descripcion"));
                model2.addElement(generos.getString("descripcion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void habilitarElementosModificarLibro(boolean habilitado){
        mLFecha.setEditable(habilitado);
        mLListaGenero.setEnabled(habilitado);
        mLPrecio.setEditable(habilitado);
        mLTitulo.setEditable(habilitado);
    }
    
    private void elementosAgregarLibro(){
        aLCodigo.setText("");
        aLFecha.setText("");
        aLListaGenero.setSelectedIndex(0);
        aLPrecio.setText("");
        aLTitulo.setText("");
    }
    
    private void elementosModificarLibro(){
        mLCodigo.setText("");
        mLFecha.setText("");
        mLListaGenero.setSelectedIndex(0);
        mLPrecio.setText("");
        mLTitulo.setText("");
    }
    
    private void mostrarDatosLibro(ResultSet libro) {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        
        model.setRowCount(0);
        try {
            String[] datos = {String.valueOf(libro.getInt("codigoLibro")), libro.getString("titulo"), libro.getString("fechaPublicacion"), String.valueOf(libro.getDouble("precio")), libro.getString("genero")};
            model.addRow(datos);
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aLCodigo;
    private javax.swing.JTextField aLFecha;
    private javax.swing.JComboBox<String> aLListaGenero;
    private javax.swing.JTextField aLPrecio;
    private javax.swing.JTextField aLTitulo;
    private javax.swing.JButton aLbtnAgregar;
    private javax.swing.JButton aLbtnCancelar;
    private javax.swing.JTextField eLCodigo;
    private javax.swing.JButton eLEliminar;
    private javax.swing.JButton eLbtnBuscar;
    private javax.swing.JButton eLbtnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JButton lLbtnLimpiar;
    private javax.swing.JButton lLbtnListar;
    private javax.swing.JTextField mLCodigo;
    private javax.swing.JTextField mLFecha;
    private javax.swing.JComboBox<String> mLListaGenero;
    private javax.swing.JTextField mLPrecio;
    private javax.swing.JTextField mLTitulo;
    private javax.swing.JButton mLbtnBuscar;
    private javax.swing.JButton mLbtnCancelar;
    private javax.swing.JButton mLbtnModificar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    
}
